import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from './comps/Navbar';
import Footer from './comps/Footer';
import ContextProvider from './comps/context';

const montserrat = Montserrat({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${montserrat.className}  antialiased flex flex-col min-h-[100vh]`}
			>
				<ContextProvider>
					<Navbar />
					{children}

					<Footer />
				</ContextProvider>
			</body>
		</html>
	);
}
